server {
    listen 443 ssl;
    server_name _;
    ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    location / {
        return 200 "docker lab-rp placeholder\n";
    }
}
